version: 2

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/ConnextProject/indra.git
            cd indra
            make start
            cd ..
            npm run test

  push-images:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && make push

  push-live-images:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && make push-live

  deploy-staging:
    machine: true
    steps:
      - run:
          command: |
            ssh ubuntu@$STAGING_URL "bash -s" <<EOF
              git clone https://github.com/ConnextProject/card.git || true
              cd card
              git fetch
              git reset --hard "origin/$CIRCLE_BRANCH"
              export DAICARD_DOMAINNAME="$STAGING_URL
              bash ops/restart.sh prod
            EOF

  deploy-live:
    machine: true
    steps:
      - run:
          command: |
            ssh ubuntu@$PRODUCTION_URL "bash -s" <<EOF
              git clone https://github.com/ConnextProject/card.git || true
              cd card
              git fetch
              git reset --hard "origin/$CIRCLE_BRANCH"
              export DAICARD_DOMAINNAME="$PRODUCTION_URL"
              export DAICARD_MODE="live"
              bash ops/restart.sh prod
            EOF

workflows:
  version: 2
  test:
    jobs:
      - test
      - push-images:
          requires:
            - test
      - push-live-images:
          filters:
            branches:
              only: master
          requires:
            - test
      - deploy-staging:
          requires:
            - push-images
      - deploy-live:
          filters:
            branches:
              only: master
          requires:
            - push-live-images
